/* eslint-disable @typescript-eslint/naming-convention */
// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface FormJson {
  $type?: string;
  FormId?: string;
  EntityLogicalName?: null;
  TabAttributes?: TabAttributes;
  Tabs?: Tabs;
  HiddenFields?: HiddenFields;
  Header?: Header;
  Footer?: Footer;
  InlineEditGridRow?: null;
  InlineQuickForms?: InlineQuickForms;
  QuickForms?: null;
  EventHandlers?: EventHandlers;
  LinkControlSections?: null;
  FormType?: number;
  SubGrids?: null;
  Views?: null;
  Charts?: null;
  CustomControlConfigurations?: CustomControlConfigurations;
  BusinessLogic?: null;
  FormLibraries?: ClientResources;
  ClientResources?: ClientResources;
  Navigation?: Navigation;
  ShowNavigationBar?: boolean;
  ShowEntityImage?: boolean;
  HeaderDensity?: string;
  ShowQuickFormBorder?: boolean;
  FormParameters?: ClientResources;
  VersionNumber?: number;
  OverallVersionNumber?: number;
  ShowInFormSelector?: boolean;
  Name?: null;
  Id?: string;
  Label?: null;
  ShowLabel?: boolean;
  Visible?: boolean;
  LabelId?: null;
}

export interface ClientResources {
  $type: string;
  $values: string[];
}

export interface CustomControlConfigurations {
  $type: string;
  $values: CustomControlConfigurationsValue[];
}

export interface CustomControlConfigurationsValue {
  $type: string;
  UniqueId: string;
  CustomControls: CustomControls;
  FormLibraries: null;
  EventHandlers: null;
  VersionNumber: number;
  OverallVersionNumber: number;
  PrimaryEntityType: null;
}

export interface CustomControls {
  $type: string;
  $values: CustomControlsValue[];
}

export interface CustomControlsValue {
  $type: string;
  CustomControlId: string;
  FormFactor: number;
  Name: string;
  DisplayNameKey: null;
  Version: null;
  Parameters: Parameters;
  ShouldOverrideControlVisible: boolean;
}

export interface Parameters {
  $type: string;
  $values: ParametersValue[];
}

export interface ParametersValue {
  $type: string;
  Name: string;
  Value: null | string;
  TargetEntities: TargetEntities | null;
  StreamObjects: null;
}

export interface TargetEntities {
  $type: string;
  $values: TargetEntitiesValue[];
}

export interface TargetEntitiesValue {
  $type: string;
  EntityLogicalName: string;
  UnboundLookupStyle: null;
  DefaultViewId: string;
  IsDeDupLookup: boolean;
}

export interface EventHandlers {
  $type: string;
  $values: EventHandlersValue[];
}

export interface EventHandlersValue {
  $type: string;
  EventName: string;
  FunctionName: string;
  LibraryName: string;
  Parameters: null | string;
  PassExecutionContext: boolean;
  AttributeName: null;
  ControlId: null | string;
  Relationship: null;
  Enabled: boolean;
  BehaviorInBulkEditForm: null;
}

export interface Footer {
  $type: string;
  Visible: boolean;
  Controls?: HiddenFields;
  AvailableForPhone?: boolean;
  Name: null;
  Id: null;
  Label: null;
  ShowLabel: boolean;
  LabelId: null;
  Sections?: Sections;
  Width?: string;
}

export interface HiddenFields {
  $type: string;
  $values: Value[];
}

export interface Value {
  $type: string;
  UniqueId?: string;
  DataFieldName: null | string;
  ClassId: string;
  Parameters: Parameters | null;
  Disabled: boolean;
  ControlLayout: number;
  RequiredLevel: number;
  Type: number;
  IsUnbound: boolean;
  IsRequired: boolean;
  EventHandlers: EventHandlers | null;
  relationship: null;
  Name: null | string;
  Id: null | string;
  Label: null;
  ShowLabel: boolean;
  Visible: boolean;
  LabelId: null | string;
}

export interface Sections {
  $type: string;
  $values: SectionsValue[];
}

export interface SectionsValue {
  $type: string;
  Rows: Rows;
  Columns: number;
  LabelWidth: number;
  CellLabel: CellLabel;
  Height: null | string;
  AvailableForPhone: boolean;
  Name: string;
  Id: string;
  Label: null;
  ShowLabel: boolean;
  Visible: boolean;
  LabelId: null;
}

export interface CellLabel {
  $type: string;
  Width: number;
  Alignment: number;
  Position: number;
}

export interface Rows {
  $type: string;
  $values: RowsValue[];
}

export interface RowsValue {
  $type: string;
  Visible: boolean;
  Height: null | string;
  Cells: Cells;
}

export interface Cells {
  $type: string;
  $values: CellsValue[];
}

export interface CellsValue {
  $type: string;
  ColSpan: number;
  RowSpan: number;
  AutoExpand: boolean;
  IsInFirstColumnOfSection: boolean;
  IsInLastColumnOfSection: boolean;
  Locklevel: number;
  UserSpacer: boolean;
  IsPreviewCell: boolean;
  IsStreamCell: boolean;
  IsChartCell: boolean;
  IsTileCell: boolean;
  Control: Value;
  AvailableForPhone: boolean;
  Name: null;
  Id: string;
  Label: null;
  ShowLabel: boolean;
  Visible: boolean;
  LabelId: null;
}

export interface Header {
  $type: string;
  ShowCommandBar: boolean;
  ShowBody: boolean;
  ShowTabNavigator: boolean;
  Controls: HiddenFields;
  AvailableForPhone: boolean;
  Name: null;
  Id: null;
  Label: null;
  ShowLabel: boolean;
  Visible: boolean;
  LabelId: null;
}

export interface InlineQuickForms {
  $type: string;
  $values: InlineQuickFormsValue[];
}

export interface InlineQuickFormsValue {
  $type: string;
  EntityName: string;
  Id: string;
}

export interface Navigation {
  $type: string;
  NavBarAreas: NavBarAreas;
  NavPaneIsvItems: NavPaneISVItems;
  NavBarByRelationshipItems: NavBarByRelationshipItems;
  NavBarItems: ClientResources;
}

export interface NavBarAreas {
  $type: string;
  NavBarAreas: ClientResources;
}

export interface NavBarByRelationshipItems {
  $type: string;
  $values: NavBarByRelationshipItemsValue[];
}

export interface NavBarByRelationshipItemsValue {
  $type: string;
  Titles: Titles;
  TooltipTitles: ClientResources;
  Privileges: Privileges | null;
  RelationshipName: string;
  Id: string;
  Area: string;
  TitleResourceId: null | string;
  Client: null;
  AvailableOffline: boolean;
  Icon: null;
  Sequence: string;
  Show: boolean;
  ViewId: null;
}

export interface Privileges {
  $type: string;
  $values: PrivilegesValue[];
}

export interface PrivilegesValue {
  $type: string;
  Entity: string;
  Privilege: string;
}

export interface Titles {
  $type: string;
  $values: TitlesValue[];
}

export interface TitlesValue {
  $type: string;
  Name: string;
  Value: string;
}

export interface NavPaneISVItems {
  $type: string;
  NavBarIsvItems: ClientResources;
}

export interface TabAttributes {
  $type: string;
  addedby: null;
  filterby: null;
  dashboardCategory: null;
  timeframe: null;
  primaryentitylogicalname: null;
  entityview: null;
  tilepresent: boolean;
}

export interface Tabs {
  $type: string;
  $values: TabsValue[];
}

export interface TabsValue {
  $type: string;
  Columns: Columns;
  EventHandlers: ClientResources;
  Expanded: boolean;
  TabHeader: ClientResources;
  TabFooter: ClientResources;
  ContentType: string;
  AvailableForPhone: boolean;
  Name: string;
  Id: string;
  Label: null;
  ShowLabel: boolean;
  Visible: boolean;
  LabelId: null;
}

export interface Columns {
  $type: string;
  $values: Footer[];
}
