import * as vscode from "vscode";
import * as fs from "fs";
import * as path from "path";
import DataversePowerToolsContext from "../context";
import { resolveTestProjectPath } from "./unitTesting";
import { activeComponentRoot } from "../components/componentDiscovery";
import { MODERN_SDK_PACKAGE, MODERN_SDK_PACKAGE_VERSION, MODERN_TARGET_FRAMEWORK, modernTargetFrameworkOf } from "./multiTarget";

// Replay a captured profile as a GENERATED UNIT TEST (#63 phase 2c, #210). The generated test runs
// the plugin IN-PROCESS: a shared harness (DvptProfileReplay.cs) decodes the profile
// (base64 → raw-DEFLATE → the profiler's `<Report>` XML → the `<Context>` element, which is a
// DataContract-serialized PluginExecutionContext), deserializes it into an IPluginExecutionContext,
// and builds the plugin's IServiceProvider — then the per-profile test does `new Plugin().Execute(sp)`.
// This uses ONLY Microsoft.Xrm.Sdk (no PluginProfiler assemblies, no AppDomain), so it actually runs
// under `dotnet test` / Test Explorer with breakpoints in your plugin. The earlier approach called
// PluginProfiler.Library.ProfilerExecutionUtility.Replay, which spins up a child AppDomain that can't
// resolve assemblies in a test host — it compiled but never ran (#210).

/** The name of the shared replay harness file written once into the test project. */
export const REPLAY_HARNESS_FILE = "DvptProfileReplay.cs";

/** The plugin type name a profile was captured for. The report is a
 * DataContract-serialized ProfilerPluginReport; TypeName is a top-level
 * element. Pure. */
export function extractProfileTypeName(profileXml: string): string | undefined {
  const match = profileXml.match(/<(?:[A-Za-z0-9]+:)?TypeName>([^<]+)<\/(?:[A-Za-z0-9]+:)?TypeName>/);
  return match?.[1]?.trim() || undefined;
}

export type ReplayTestFramework = "mstest" | "xunit" | "nunit";

export interface ReplayTestOptions {
  framework: ReplayTestFramework;
  namespaceName: string;
  className: string;
  /** Fully-qualified plugin type from the profile. */
  pluginTypeName: string;
  /** Profile file name under <componentRoot>/profiles/. */
  profileFileName: string;
}

const FRAMEWORK_PARTS: Record<ReplayTestFramework, { using: string; classAttribute: string; methodAttribute: string }> = {
  mstest: { using: "Microsoft.VisualStudio.TestTools.UnitTesting", classAttribute: "[TestClass]", methodAttribute: "[TestMethod]" },
  nunit: { using: "NUnit.Framework", classAttribute: "[TestFixture]", methodAttribute: "[Test]" },
  xunit: { using: "Xunit", classAttribute: "", methodAttribute: "[Fact]" },
};

/** C# source of the per-profile replay test — small; the heavy lifting is in the shared harness
 * (replayHarnessSource / DvptProfileReplay.cs). Instantiates the plugin directly (via the test's
 * project reference) and runs it with the captured context, so a failing captured run reproduces
 * here for debugging, and a clean one is green. Pure. */
export function replayTestSource(options: ReplayTestOptions): string {
  const parts = FRAMEWORK_PARTS[options.framework];
  const classAttributeLine = parts.classAttribute ? `    ${parts.classAttribute}\n` : "";
  return `// Generated by Dataverse PowerTools — replay of a captured plugin profile (#63/#210).
// Set breakpoints inside ${options.pluginTypeName}.Execute and DEBUG this test from the Test Explorer:
// it deserializes the captured execution context and invokes the plugin IN-PROCESS (no live org). If
// your plugin calls IOrganizationService, replace DvptReplay.ReplayOrganizationService with a mock
// (e.g. FakeXrmEasy) to exercise those branches.
using DvptReplay;
using ${parts.using};

namespace ${options.namespaceName}
{
${classAttributeLine}    public class ${options.className}
    {
        ${parts.methodAttribute}
        public void ReplayCapturedProfile()
        {
            var context = ProfileReplay.LoadContext(ProfileReplay.FindProfile("${options.profileFileName}"));
            var plugin = new ${options.pluginTypeName}(null, null);
            plugin.Execute(ProfileReplay.CreateServiceProvider(context));
        }
    }
}
`;
}

/** C# source of the shared replay harness (written once as DvptProfileReplay.cs). Decodes a captured
 * profile into an IPluginExecutionContext and builds the plugin IServiceProvider — Microsoft.Xrm.Sdk
 * only, no PluginProfiler assemblies, no AppDomain (that's why it actually runs; see #210). Pure. */
export function replayHarnessSource(): string {
  return `// Generated by Dataverse PowerTools — shared harness for replaying captured plugin profiles (#63/#210).
// A profile is base64( raw-DEFLATE( <Report> XML ) ); its <Context> element is a DataContract-serialized
// PluginExecutionContext. This deserializes it into an IPluginExecutionContext and builds the plugin's
// IServiceProvider, so a generated Replay_*.cs can run your plugin IN-PROCESS with the real captured
// context. Uses only Microsoft.Xrm.Sdk — runs under dotnet test / Test Explorer with breakpoints.
using System;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Xml;
using System.Xml.Linq;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;

namespace DvptReplay
{
    [DataContract(Name = "PluginExecutionContext", Namespace = "")]
    internal class CapturedPluginContext : IPluginExecutionContext
    {
        [DataMember] public Guid BusinessUnitId { get; set; }
        [DataMember] public Guid CorrelationId { get; set; }
        [DataMember] public int Depth { get; set; }
        [DataMember] public Guid InitiatingUserId { get; set; }
        [DataMember] public ParameterCollection InputParameters { get; set; }
        [DataMember] public bool IsExecutingOffline { get; set; }
        [DataMember] public bool IsInTransaction { get; set; }
        [DataMember] public bool IsOfflinePlayback { get; set; }
        [DataMember] public int IsolationMode { get; set; }
        [DataMember] public string MessageName { get; set; }
        [DataMember] public int Mode { get; set; }
        [DataMember] public DateTime OperationCreatedOn { get; set; }
        [DataMember] public Guid OperationId { get; set; }
        [DataMember] public Guid OrganizationId { get; set; }
        [DataMember] public string OrganizationName { get; set; }
        [DataMember] public ParameterCollection OutputParameters { get; set; }
        [DataMember] public EntityReference OwningExtension { get; set; }
        [DataMember] public EntityImageCollection PostEntityImages { get; set; }
        [DataMember] public EntityImageCollection PreEntityImages { get; set; }
        [DataMember] public Guid PrimaryEntityId { get; set; }
        [DataMember] public string PrimaryEntityName { get; set; }
        [DataMember] public Guid? RequestId { get; set; }
        [DataMember] public string SecondaryEntityName { get; set; }
        [DataMember] public ParameterCollection SharedVariables { get; set; }
        [DataMember] public Guid UserId { get; set; }
        [DataMember(Name = "ParentContext")] public CapturedPluginContext ParentCaptured { get; set; }
        [DataMember] public int Stage { get; set; }
        public IPluginExecutionContext ParentContext { get { return ParentCaptured; } }
    }

    internal sealed class ReplayTracingService : ITracingService
    {
        public void Trace(string format, params object[] args)
        {
            try { Console.WriteLine(args != null && args.Length > 0 ? string.Format(format, args) : format); }
            catch { Console.WriteLine(format); }
        }
    }

    // Throws a clear message if the plugin makes an org call — the profile captures those calls but this
    // harness doesn't re-serve them. Replace with your own mock (e.g. FakeXrmEasy) for org-dependent code.
    internal sealed class ReplayOrganizationService : IOrganizationService
    {
        private static Exception NotReplayed(string op)
        {
            return new NotSupportedException("Replay: the plugin called IOrganizationService." + op +
                " — this generated harness does not re-serve captured org calls. Replace DvptReplay.ReplayOrganizationService with a mock to exercise this path.");
        }
        public Guid Create(Entity entity) { throw NotReplayed("Create"); }
        public Entity Retrieve(string entityName, Guid id, ColumnSet columnSet) { throw NotReplayed("Retrieve"); }
        public void Update(Entity entity) { throw NotReplayed("Update"); }
        public void Delete(string entityName, Guid id) { throw NotReplayed("Delete"); }
        public OrganizationResponse Execute(OrganizationRequest request) { throw NotReplayed("Execute"); }
        public void Associate(string entityName, Guid entityId, Relationship relationship, EntityReferenceCollection relatedEntities) { throw NotReplayed("Associate"); }
        public void Disassociate(string entityName, Guid entityId, Relationship relationship, EntityReferenceCollection relatedEntities) { throw NotReplayed("Disassociate"); }
        public EntityCollection RetrieveMultiple(QueryBase query) { throw NotReplayed("RetrieveMultiple"); }
    }

    internal sealed class ReplayOrganizationServiceFactory : IOrganizationServiceFactory
    {
        public IOrganizationService CreateOrganizationService(Guid? userId) { return new ReplayOrganizationService(); }
    }

    internal sealed class ReplayServiceProvider : IServiceProvider
    {
        private readonly IPluginExecutionContext _context;
        private readonly ITracingService _tracing = new ReplayTracingService();
        public ReplayServiceProvider(IPluginExecutionContext context) { _context = context; }
        public object GetService(Type serviceType)
        {
            if (serviceType == typeof(IPluginExecutionContext) || serviceType == typeof(IExecutionContext)) return _context;
            if (serviceType == typeof(ITracingService)) return _tracing;
            if (serviceType == typeof(IOrganizationServiceFactory)) return new ReplayOrganizationServiceFactory();
            return null;
        }
    }

    public static class ProfileReplay
    {
        public static IPluginExecutionContext LoadContext(string profilePath)
        {
            var compressed = Convert.FromBase64String(File.ReadAllText(profilePath).Trim());
            string reportXml;
            using (var input = new MemoryStream(compressed))
            using (var deflate = new DeflateStream(input, CompressionMode.Decompress))
            using (var output = new MemoryStream())
            {
                deflate.CopyTo(output);
                reportXml = Encoding.UTF8.GetString(output.ToArray());
            }
            var contextXml = XDocument.Parse(reportXml).Descendants().First(e => e.Name.LocalName == "Context").Value;
            using (var reader = XmlReader.Create(new StringReader(contextXml)))
            {
                var serializer = new DataContractSerializer(typeof(object), new[] { typeof(CapturedPluginContext) });
                return (IPluginExecutionContext) serializer.ReadObject(reader);
            }
        }

        public static IServiceProvider CreateServiceProvider(IPluginExecutionContext context)
        {
            return new ReplayServiceProvider(context);
        }

        // The profile lives in <workspace>/profiles; walk up from the test bin so it's found regardless
        // of build configuration / TFM folder depth.
        public static string FindProfile(string fileName)
        {
            var dir = new DirectoryInfo(AppDomain.CurrentDomain.BaseDirectory);
            while (dir != null)
            {
                var candidate = Path.Combine(dir.FullName, "profiles", fileName);
                if (File.Exists(candidate)) return candidate;
                dir = dir.Parent;
            }
            throw new FileNotFoundException("Could not find profiles/" + fileName + " above the test directory.");
        }
    }
}
`;
}

/** Ensure a test .csproj can build+run the replay harness (idempotent, pure): a direct
 * Microsoft.Xrm.Sdk reference (the plugin project's is PrivateAssets and doesn't flow — CS0012
 * otherwise). No PluginProfiler assemblies — the harness is standalone (#210).
 *
 * WHICH package supplies Microsoft.Xrm.Sdk depends on the test project's framework (#269): a
 * modern project (net8.0, which is what a multi-targeted plug-in gives it, and the only kind
 * `dotnet test` can run without a .NET Framework test host) needs the netstandard2.0 assembly out
 * of Microsoft.PowerPlatform.Dataverse.Client. Injecting the Framework-only
 * Microsoft.CrmSdk.CoreAssemblies there — which is what this used to do unconditionally — makes
 * restore fail. The binding redirects are Framework-only too; on net8.0 they are meaningless. */
export function ensureReplayCsproj(csprojXml: string): string {
  let out = csprojXml;
  const modern = modernTargetFrameworkOf(csprojXml) !== undefined;

  if (modern) {
    if (!out.includes(MODERN_SDK_PACKAGE)) {
      const itemGroup =
        `  <ItemGroup>\n    <!-- Replay harness needs Microsoft.Xrm.Sdk directly; on ${MODERN_TARGET_FRAMEWORK} it comes from the\n` +
        `         netstandard2.0 client package (Dataverse PowerTools #210/#269) -->\n` +
        `    <PackageReference Include="${MODERN_SDK_PACKAGE}" Version="${MODERN_SDK_PACKAGE_VERSION}" />\n  </ItemGroup>\n`;
      out = out.replace(/<\/Project>\s*$/, `${itemGroup}</Project>\n`);
    }
    return out;
  }

  if (!/Microsoft\.CrmSdk\.CoreAssemblies/.test(out)) {
    const itemGroup = `  <ItemGroup>\n    <!-- Replay harness needs Microsoft.Xrm.Sdk directly (Dataverse PowerTools #210) -->\n    <PackageReference Include="Microsoft.CrmSdk.CoreAssemblies" Version="9.0.2.*" />\n  </ItemGroup>\n`;
    out = out.replace(/<\/Project>\s*$/, `${itemGroup}</Project>\n`);
  }
  if (!/AutoGenerateBindingRedirects/.test(out)) {
    out = out.replace(
      /<\/PropertyGroup>/,
      `  <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>\n    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>\n  </PropertyGroup>`,
    );
  }
  return out;
}

/** File-name-safe class name for the generated test. Pure. */
export function replayClassName(pluginTypeName: string, stamp: string): string {
  const shortType = pluginTypeName.split(".").pop() || "Plugin";
  return `Replay_${shortType.replace(/[^A-Za-z0-9_]+/g, "_")}_${stamp}`;
}

/** Recover the plugin type from a downloaded profile's file name. The download flow
 * (profileFileName) names files `<TypeName>_<yyyymmdd-hhmmss>.profile[.xml]`, so when the
 * profile stream itself has no plain-text type, the name is the reliable source. Returns
 * undefined for names that don't match the pattern (e.g. an arbitrary browsed-in file). Pure. */
export function extractTypeFromProfileFileName(fileName: string): string | undefined {
  const base = fileName.replace(/\.profile(\.xml)?$/i, "");
  const match = base.match(/^([A-Za-z_][A-Za-z0-9_.]*)_(?:\d{8}-\d{6}|unknown-time)$/);
  return match?.[1];
}

/** Open a file dialog for a saved profile (PRT-exported XML). */
async function browseForProfile(componentRoot: string): Promise<string | undefined> {
  const picked = await vscode.window.showOpenDialog({
    canSelectMany: false,
    defaultUri: vscode.Uri.file(componentRoot),
    openLabel: "Replay this profile",
    filters: { "Plug-in profile": ["xml", "profile"], "All files": ["*"] }, // eslint-disable-line @typescript-eslint/naming-convention
  });
  return picked?.[0]?.fsPath;
}

export async function generatePluginReplayTest(context: DataversePowerToolsContext): Promise<void> {
  const componentRoot = activeComponentRoot(context);
  if (!componentRoot) {
    vscode.window.showErrorMessage("No workspace folder is open.");
    return;
  }

  const testCsprojPath = await resolveTestProjectPath(context, componentRoot);
  if (!testCsprojPath) {
    vscode.window.showWarningMessage("No test project found — run 'Setup Plugin Unit Testing' first; the replay runs as a normal unit test.");
    return;
  }

  // A profile comes from Download Captured Profiles OR is dropped into profiles/
  // by the user (captured via the Plugin Registration Tool — same file the PRT
  // "Replay Plug-in Execution" dialog's Profile Location field takes). When none
  // is present, offer a file picker so any saved profile works.
  const profilesDir = path.join(componentRoot, "profiles");
  const profileFiles = fs.existsSync(profilesDir) ? (await fs.promises.readdir(profilesDir)).filter((file) => file.includes(".profile")) : [];
  let profilePath: string | undefined;
  if (profileFiles.length === 1) {
    profilePath = path.join(profilesDir, profileFiles[0]);
  } else if (profileFiles.length > 1) {
    const picked = await vscode.window.showQuickPick([...profileFiles, "$(folder-opened) Browse for a profile file…"], {
      placeHolder: "Replay which profile?",
      ignoreFocusOut: true,
    });
    profilePath = picked?.startsWith("$(folder") ? await browseForProfile(componentRoot) : picked ? path.join(profilesDir, picked) : undefined;
  } else {
    const choice = await vscode.window.showInformationMessage(
      "No profiles in profiles/. Capture one in the Plugin Registration Tool (Start Profiling → Persist to Entity, trigger the plug-in), then Download it — or browse for a saved profile file.",
      "Browse for a file…",
      "Download profiles",
    );
    if (choice === "Download profiles") {
      await vscode.commands.executeCommand("dataverse-powertools.downloadPluginProfiles");
      return;
    }
    profilePath = choice === "Browse for a file…" ? await browseForProfile(componentRoot) : undefined;
  }
  if (!profilePath) {
    return;
  }
  const picked = path.basename(profilePath);
  // Copy a browsed-in file into profiles/ so the generated test's FindProfile locates it.
  if (path.dirname(path.resolve(profilePath)) !== path.resolve(profilesDir)) {
    await fs.promises.mkdir(profilesDir, { recursive: true });
    await fs.promises.copyFile(profilePath, path.join(profilesDir, picked));
  }

  const profileXml = await fs.promises.readFile(path.join(profilesDir, picked), "utf8");
  // The profiler's mbs_profile stream is base64/compressed (no plain-text type), so fall
  // back to the type encoded in the downloaded file name, then finally ask.
  let pluginTypeName = extractProfileTypeName(profileXml) ?? extractTypeFromProfileFileName(picked);
  if (!pluginTypeName) {
    pluginTypeName = await vscode.window.showInputBox({ prompt: "Fully-qualified plugin type name for this profile", ignoreFocusOut: true });
  }
  if (!pluginTypeName) {
    return;
  }

  const testProjectDir = path.dirname(testCsprojPath);
  const testProjectName = path.basename(testCsprojPath, ".csproj");
  const framework = (context.projectSettings.pluginUnitTestingFramework || "xunit") as ReplayTestFramework;
  const stamp = new Date().toISOString().replace(/[-:T]/g, "").slice(0, 14);
  const className = replayClassName(pluginTypeName, stamp);

  // Ensure the test project can build+run the harness (a direct Microsoft.Xrm.Sdk reference),
  // idempotent. WHICH package supplies it depends on the framework (#269), so say which was used
  // rather than always claiming binding redirects — those are Framework-only and a net8.0 project
  // never gets them.
  const csprojXml = await fs.promises.readFile(testCsprojPath, "utf8");
  const patched = ensureReplayCsproj(csprojXml);
  if (patched !== csprojXml) {
    await fs.promises.writeFile(testCsprojPath, patched);
    const modernTarget = modernTargetFrameworkOf(csprojXml);
    context.channel.appendLine(
      modernTarget
        ? `[Profiler] Wired ${testProjectName}.csproj for the replay harness (Microsoft.Xrm.Sdk via ${MODERN_SDK_PACKAGE}, ${modernTarget}).`
        : `[Profiler] Wired ${testProjectName}.csproj for the replay harness (Microsoft.Xrm.Sdk + binding redirects).`,
    );
  }

  // Write the shared replay harness once (all Replay_*.cs in this project use it).
  const harnessPath = path.join(testProjectDir, REPLAY_HARNESS_FILE);
  if (!fs.existsSync(harnessPath)) {
    await fs.promises.writeFile(harnessPath, replayHarnessSource());
    context.channel.appendLine(`[Profiler] Wrote replay harness ${harnessPath}`);
  }

  const testFilePath = path.join(testProjectDir, `${className}.cs`);
  await fs.promises.writeFile(
    testFilePath,
    replayTestSource({
      framework,
      namespaceName: testProjectName.replace(/[^A-Za-z0-9_.]/g, "_"),
      className,
      pluginTypeName,
      profileFileName: picked,
    }),
  );
  context.channel.appendLine(`[Profiler] Generated ${testFilePath}`);

  const document = await vscode.workspace.openTextDocument(testFilePath);
  await vscode.window.showTextDocument(document);
  vscode.window.showInformationMessage(`Replay test ${className} generated — set breakpoints in ${pluginTypeName} and debug it from the Test Explorer.`);
}
