import * as vscode from "vscode";
import * as fs from "fs";
import * as path from "path";
import DataversePowerToolsContext from "../context";
import { ensureProfilerAssemblies, PROFILER_ASSEMBLIES, PROFILER_LIB_DIR } from "./profilerAssets";
import { resolveTestProjectPath } from "./unitTesting";
import { activeComponentRoot } from "../components/componentDiscovery";

// Replay a captured profile as a GENERATED UNIT TEST (#63 phase 2c). No custom
// replay host: the test deserializes the profile with PluginProfiler.Library
// (ProfilerExecutionUtility.Replay) and invokes the plugin's Execute in-process,
// so breakpoints/stepping come from the debuggable `dotnet test` infrastructure
// that already exists (Test Explorer, #84). Windows-only in practice (net462
// test host) — the same constraint the Plugin Registration Tool has.

/** The plugin type name a profile was captured for. The report is a
 * DataContract-serialized ProfilerPluginReport; TypeName is a top-level
 * element. Pure. */
export function extractProfileTypeName(profileXml: string): string | undefined {
  const match = profileXml.match(/<(?:[A-Za-z0-9]+:)?TypeName>([^<]+)<\/(?:[A-Za-z0-9]+:)?TypeName>/);
  return match?.[1]?.trim() || undefined;
}

export type ReplayTestFramework = "mstest" | "xunit" | "nunit";

export interface ReplayTestOptions {
  framework: ReplayTestFramework;
  namespaceName: string;
  className: string;
  /** Fully-qualified plugin type from the profile. */
  pluginTypeName: string;
  /** The built plugin assembly file name (copied into the test bin by the project reference). */
  pluginAssemblyFileName: string;
  /** Profile file name under <componentRoot>/profiles/. */
  profileFileName: string;
}

const FRAMEWORK_PARTS: Record<ReplayTestFramework, { using: string; classAttribute: string; methodAttribute: string; assertNull: string }> = {
  mstest: { using: "Microsoft.VisualStudio.TestTools.UnitTesting", classAttribute: "[TestClass]", methodAttribute: "[TestMethod]", assertNull: "Assert.IsNull" },
  nunit: { using: "NUnit.Framework", classAttribute: "[TestFixture]", methodAttribute: "[Test]", assertNull: "Assert.IsNull" },
  xunit: { using: "Xunit", classAttribute: "", methodAttribute: "[Fact]", assertNull: "Assert.Null" },
};

/** C# source of the generated replay test. Pure. */
export function replayTestSource(options: ReplayTestOptions): string {
  const parts = FRAMEWORK_PARTS[options.framework];
  const classAttributeLine = parts.classAttribute ? `    ${parts.classAttribute}\n` : "";
  return `// Generated by Dataverse PowerTools — replay of a captured plugin profile (#63).
// Set breakpoints inside ${options.pluginTypeName}.Execute and DEBUG this test from the
// Test Explorer: the replay deserializes the captured execution context and invokes the
// plugin in-process with the profiler's stand-in services (no live org needed).
using System;
using System.IO;
using ${parts.using};
using PluginProfiler.Library;
using PluginProfiler.Library.Reporting;

namespace ${options.namespaceName}
{
${classAttributeLine}    public class ${options.className}
    {
        ${parts.methodAttribute}
        public void ReplayCapturedProfile()
        {
            var profilePath = FindProfile("${options.profileFileName}");
            var assemblyPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "${options.pluginAssemblyFileName}");
            var operation = new PluginOperationConfiguration(assemblyPath, "${options.pluginTypeName}", profilePath, null);

            var report = ProfilerExecutionUtility.Replay(
                PluginPermissions.NonIsolated,
                operation,
                new ProfilerReportingConfiguration(),
                new ProfilerConsoleTracingService(),
                null);

            ${parts.assertNull}(report.ProfilerReport == null ? null : report.ProfilerReport.ExecutionException);
        }

        // The profile lives in <workspace>/profiles; walk up from the test bin so the
        // test works regardless of build configuration/TFM folder depth.
        private static string FindProfile(string fileName)
        {
            var dir = new DirectoryInfo(AppDomain.CurrentDomain.BaseDirectory);
            while (dir != null)
            {
                var candidate = Path.Combine(dir.FullName, "profiles", fileName);
                if (File.Exists(candidate))
                {
                    return candidate;
                }
                dir = dir.Parent;
            }
            throw new FileNotFoundException("Could not find profiles/" + fileName + " above the test directory.");
        }
    }
}
`;
}

/** Add the profiler assembly references to a test .csproj (idempotent). Pure. */
export function csprojWithProfilerRefs(csprojXml: string, assemblyNames: readonly string[], relativeLibDir: string): string {
  if (csprojXml.includes("PluginProfiler.Library")) {
    return csprojXml;
  }
  const references = assemblyNames
    .map((file) => {
      const name = file.replace(/\.dll$/i, "");
      // Microsoft.Xrm.Sdk is a COMPILE-time reference only (Private=false): the test host already
      // gets it transitively (from the plugin project / DataverseUnitTest), so copying the profiler's
      // copy too would raise "conflicts between different versions". The profiler DLLs are copy-local.
      const copyLocal = !/^microsoft\.xrm\.sdk$/i.test(name);
      return `    <Reference Include="${name}">\n      <HintPath>${relativeLibDir}\\${file}</HintPath>\n      <Private>${copyLocal}</Private>\n    </Reference>`;
    })
    .join("\n");
  const itemGroup = `  <ItemGroup>\n    <!-- Plugin Profiler replay assemblies (Dataverse PowerTools, #63) -->\n${references}\n  </ItemGroup>\n`;
  return csprojXml.replace(/<\/Project>\s*$/, `${itemGroup}</Project>\n`);
}

/** File-name-safe class name for the generated test. Pure. */
export function replayClassName(pluginTypeName: string, stamp: string): string {
  const shortType = pluginTypeName.split(".").pop() || "Plugin";
  return `Replay_${shortType.replace(/[^A-Za-z0-9_]+/g, "_")}_${stamp}`;
}

/** Recover the plugin type from a downloaded profile's file name. The download flow
 * (profileFileName) names files `<TypeName>_<yyyymmdd-hhmmss>.profile[.xml]`, so when the
 * profile stream itself has no plain-text type, the name is the reliable source. Returns
 * undefined for names that don't match the pattern (e.g. an arbitrary browsed-in file). Pure. */
export function extractTypeFromProfileFileName(fileName: string): string | undefined {
  const base = fileName.replace(/\.profile(\.xml)?$/i, "");
  const match = base.match(/^([A-Za-z_][A-Za-z0-9_.]*)_(?:\d{8}-\d{6}|unknown-time)$/);
  return match?.[1];
}

/** Open a file dialog for a saved profile (PRT-exported XML). */
async function browseForProfile(componentRoot: string): Promise<string | undefined> {
  const picked = await vscode.window.showOpenDialog({
    canSelectMany: false,
    defaultUri: vscode.Uri.file(componentRoot),
    openLabel: "Replay this profile",
    filters: { "Plug-in profile": ["xml", "profile"], "All files": ["*"] }, // eslint-disable-line @typescript-eslint/naming-convention
  });
  return picked?.[0]?.fsPath;
}

export async function generatePluginReplayTest(context: DataversePowerToolsContext): Promise<void> {
  const componentRoot = activeComponentRoot(context);
  if (!componentRoot) {
    vscode.window.showErrorMessage("No workspace folder is open.");
    return;
  }

  const testCsprojPath = await resolveTestProjectPath(context, componentRoot);
  if (!testCsprojPath) {
    vscode.window.showWarningMessage("No test project found — run 'Setup Plugin Unit Testing' first; the replay runs as a normal unit test.");
    return;
  }

  // A profile comes from Download Captured Profiles OR is dropped into profiles/
  // by the user (captured via the Plugin Registration Tool — same file the PRT
  // "Replay Plug-in Execution" dialog's Profile Location field takes). When none
  // is present, offer a file picker so any saved profile works.
  const profilesDir = path.join(componentRoot, "profiles");
  const profileFiles = fs.existsSync(profilesDir) ? (await fs.promises.readdir(profilesDir)).filter((file) => file.includes(".profile")) : [];
  let profilePath: string | undefined;
  if (profileFiles.length === 1) {
    profilePath = path.join(profilesDir, profileFiles[0]);
  } else if (profileFiles.length > 1) {
    const picked = await vscode.window.showQuickPick([...profileFiles, "$(folder-opened) Browse for a profile file…"], {
      placeHolder: "Replay which profile?",
      ignoreFocusOut: true,
    });
    profilePath = picked?.startsWith("$(folder") ? await browseForProfile(componentRoot) : picked ? path.join(profilesDir, picked) : undefined;
  } else {
    const choice = await vscode.window.showInformationMessage(
      "No profiles in profiles/. Capture one in the Plugin Registration Tool (Start Profiling → Persist to Entity, trigger the plug-in), then Download it — or browse for a saved profile file.",
      "Browse for a file…",
      "Download profiles",
    );
    if (choice === "Download profiles") {
      await vscode.commands.executeCommand("dataverse-powertools.downloadPluginProfiles");
      return;
    }
    profilePath = choice === "Browse for a file…" ? await browseForProfile(componentRoot) : undefined;
  }
  if (!profilePath) {
    return;
  }
  const picked = path.basename(profilePath);
  // Copy a browsed-in file into profiles/ so the generated test's FindProfile locates it.
  if (path.dirname(path.resolve(profilePath)) !== path.resolve(profilesDir)) {
    await fs.promises.mkdir(profilesDir, { recursive: true });
    await fs.promises.copyFile(profilePath, path.join(profilesDir, picked));
  }

  const profileXml = await fs.promises.readFile(path.join(profilesDir, picked), "utf8");
  // The profiler's mbs_profile stream is base64/compressed (no plain-text type), so fall
  // back to the type encoded in the downloaded file name, then finally ask.
  let pluginTypeName = extractProfileTypeName(profileXml) ?? extractTypeFromProfileFileName(picked);
  if (!pluginTypeName) {
    pluginTypeName = await vscode.window.showInputBox({ prompt: "Fully-qualified plugin type name for this profile", ignoreFocusOut: true });
  }
  if (!pluginTypeName) {
    return;
  }

  const libDir = await ensureProfilerAssemblies(context, componentRoot);
  if (!libDir) {
    return;
  }

  const testProjectDir = path.dirname(testCsprojPath);
  const testProjectName = path.basename(testCsprojPath, ".csproj");
  const framework = (context.projectSettings.pluginUnitTestingFramework || "xunit") as ReplayTestFramework;
  const pluginAssemblyFileName = `${context.projectSettings.pluginProjectName || "Plugin"}.dll`;
  const stamp = new Date().toISOString().replace(/[-:T]/g, "").slice(0, 14);
  const className = replayClassName(pluginTypeName, stamp);

  // Reference the profiler assemblies from the test project (idempotent).
  const csprojXml = await fs.promises.readFile(testCsprojPath, "utf8");
  const patched = csprojWithProfilerRefs(csprojXml, PROFILER_ASSEMBLIES, `..\\${PROFILER_LIB_DIR}`);
  if (patched !== csprojXml) {
    await fs.promises.writeFile(testCsprojPath, patched);
    context.channel.appendLine(`[Profiler] Added replay assembly references to ${testProjectName}.csproj`);
  }

  const testFilePath = path.join(testProjectDir, `${className}.cs`);
  await fs.promises.writeFile(
    testFilePath,
    replayTestSource({
      framework,
      namespaceName: testProjectName.replace(/[^A-Za-z0-9_.]/g, "_"),
      className,
      pluginTypeName,
      pluginAssemblyFileName,
      profileFileName: picked,
    }),
  );
  context.channel.appendLine(`[Profiler] Generated ${testFilePath}`);

  const document = await vscode.workspace.openTextDocument(testFilePath);
  await vscode.window.showTextDocument(document);
  vscode.window.showInformationMessage(`Replay test ${className} generated — set breakpoints in ${pluginTypeName} and debug it from the Test Explorer.`);
}
