import * as vscode from "vscode";
import * as fs from "fs";
import * as path from "path";
import DataversePowerToolsContext from "../context";
import { ensureProfilerAssemblies, PROFILER_ASSEMBLIES, PROFILER_LIB_DIR } from "./profilerAssets";
import { resolveTestProjectPath } from "./unitTesting";
import { activeComponentRoot } from "../components/componentDiscovery";

// Replay a captured profile as a GENERATED UNIT TEST (#63 phase 2c). No custom
// replay host: the test deserializes the profile with PluginProfiler.Library
// (ProfilerExecutionUtility.Replay) and invokes the plugin's Execute in-process,
// so breakpoints/stepping come from the debuggable `dotnet test` infrastructure
// that already exists (Test Explorer, #84). Windows-only in practice (net462
// test host) — the same constraint the Plugin Registration Tool has.

/** The plugin type name a profile was captured for. The report is a
 * DataContract-serialized ProfilerPluginReport; TypeName is a top-level
 * element. Pure. */
export function extractProfileTypeName(profileXml: string): string | undefined {
  const match = profileXml.match(/<(?:[A-Za-z0-9]+:)?TypeName>([^<]+)<\/(?:[A-Za-z0-9]+:)?TypeName>/);
  return match?.[1]?.trim() || undefined;
}

export type ReplayTestFramework = "mstest" | "xunit" | "nunit";

export interface ReplayTestOptions {
  framework: ReplayTestFramework;
  namespaceName: string;
  className: string;
  /** Fully-qualified plugin type from the profile. */
  pluginTypeName: string;
  /** The built plugin assembly file name (copied into the test bin by the project reference). */
  pluginAssemblyFileName: string;
  /** Profile file name under <componentRoot>/profiles/. */
  profileFileName: string;
}

const FRAMEWORK_PARTS: Record<ReplayTestFramework, { using: string; classAttribute: string; methodAttribute: string; assertNull: string }> = {
  mstest: { using: "Microsoft.VisualStudio.TestTools.UnitTesting", classAttribute: "[TestClass]", methodAttribute: "[TestMethod]", assertNull: "Assert.IsNull" },
  nunit: { using: "NUnit.Framework", classAttribute: "[TestFixture]", methodAttribute: "[Test]", assertNull: "Assert.IsNull" },
  xunit: { using: "Xunit", classAttribute: "", methodAttribute: "[Fact]", assertNull: "Assert.Null" },
};

/** C# source of the generated replay test. Pure. */
export function replayTestSource(options: ReplayTestOptions): string {
  const parts = FRAMEWORK_PARTS[options.framework];
  const classAttributeLine = parts.classAttribute ? `    ${parts.classAttribute}\n` : "";
  return `// Generated by Dataverse PowerTools — replay of a captured plugin profile (#63).
// Set breakpoints inside ${options.pluginTypeName}.Execute and DEBUG this test from the
// Test Explorer: the replay deserializes the captured execution context and invokes the
// plugin in-process with the profiler's stand-in services (no live org needed).
using System;
using System.IO;
using ${parts.using};
using PluginProfiler.Library;
using PluginProfiler.Library.Reporting;

namespace ${options.namespaceName}
{
${classAttributeLine}    public class ${options.className}
    {
        ${parts.methodAttribute}
        public void ReplayCapturedProfile()
        {
            var profilePath = FindProfile("${options.profileFileName}");
            var assemblyPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "${options.pluginAssemblyFileName}");
            var operation = new PluginOperationConfiguration(assemblyPath, "${options.pluginTypeName}", profilePath, null);

            var report = ProfilerExecutionUtility.Replay(
                PluginPermissions.NonIsolated,
                operation,
                new ProfilerReportingConfiguration(),
                new ProfilerConsoleTracingService(),
                null);

            ${parts.assertNull}(report.ProfilerReport == null ? null : report.ProfilerReport.ExecutionException);
        }

        // The profile lives in <workspace>/profiles; walk up from the test bin so the
        // test works regardless of build configuration/TFM folder depth.
        private static string FindProfile(string fileName)
        {
            var dir = new DirectoryInfo(AppDomain.CurrentDomain.BaseDirectory);
            while (dir != null)
            {
                var candidate = Path.Combine(dir.FullName, "profiles", fileName);
                if (File.Exists(candidate))
                {
                    return candidate;
                }
                dir = dir.Parent;
            }
            throw new FileNotFoundException("Could not find profiles/" + fileName + " above the test directory.");
        }
    }
}
`;
}

/** Add the profiler assembly references to a test .csproj (idempotent). Pure. */
export function csprojWithProfilerRefs(csprojXml: string, assemblyNames: readonly string[], relativeLibDir: string): string {
  if (csprojXml.includes("PluginProfiler.Library")) {
    return csprojXml;
  }
  const references = assemblyNames
    .map((file) => {
      const name = file.replace(/\.dll$/i, "");
      return `    <Reference Include="${name}">\n      <HintPath>${relativeLibDir}\\${file}</HintPath>\n      <Private>true</Private>\n    </Reference>`;
    })
    .join("\n");
  const itemGroup = `  <ItemGroup>\n    <!-- Plugin Profiler replay assemblies (Dataverse PowerTools, #63) -->\n${references}\n  </ItemGroup>\n`;
  return csprojXml.replace(/<\/Project>\s*$/, `${itemGroup}</Project>\n`);
}

/** File-name-safe class name for the generated test. Pure. */
export function replayClassName(pluginTypeName: string, stamp: string): string {
  const shortType = pluginTypeName.split(".").pop() || "Plugin";
  return `Replay_${shortType.replace(/[^A-Za-z0-9_]+/g, "_")}_${stamp}`;
}

export async function generatePluginReplayTest(context: DataversePowerToolsContext): Promise<void> {
  const componentRoot = activeComponentRoot(context);
  if (!componentRoot) {
    vscode.window.showErrorMessage("No workspace folder is open.");
    return;
  }

  const testCsprojPath = await resolveTestProjectPath(context, componentRoot);
  if (!testCsprojPath) {
    vscode.window.showWarningMessage("No test project found — run 'Setup Plugin Unit Testing' first; the replay runs as a normal unit test.");
    return;
  }

  // Pick a downloaded profile (phase 2a puts them in profiles/).
  const profilesDir = path.join(componentRoot, "profiles");
  const profileFiles = fs.existsSync(profilesDir) ? (await fs.promises.readdir(profilesDir)).filter((file) => file.includes(".profile")) : [];
  if (profileFiles.length === 0) {
    vscode.window.showWarningMessage("No downloaded profiles in profiles/ — run 'Download Captured Profiles' first.");
    return;
  }
  const picked = profileFiles.length === 1 ? profileFiles[0] : await vscode.window.showQuickPick(profileFiles, { placeHolder: "Replay which profile?", ignoreFocusOut: true });
  if (!picked) {
    return;
  }

  const profileXml = await fs.promises.readFile(path.join(profilesDir, picked), "utf8");
  let pluginTypeName = extractProfileTypeName(profileXml);
  if (!pluginTypeName) {
    pluginTypeName = await vscode.window.showInputBox({ prompt: "Fully-qualified plugin type name for this profile", ignoreFocusOut: true });
  }
  if (!pluginTypeName) {
    return;
  }

  const libDir = await ensureProfilerAssemblies(context, componentRoot);
  if (!libDir) {
    return;
  }

  const testProjectDir = path.dirname(testCsprojPath);
  const testProjectName = path.basename(testCsprojPath, ".csproj");
  const framework = (context.projectSettings.pluginUnitTestingFramework || "xunit") as ReplayTestFramework;
  const pluginAssemblyFileName = `${context.projectSettings.pluginProjectName || "Plugin"}.dll`;
  const stamp = new Date().toISOString().replace(/[-:T]/g, "").slice(0, 14);
  const className = replayClassName(pluginTypeName, stamp);

  // Reference the profiler assemblies from the test project (idempotent).
  const csprojXml = await fs.promises.readFile(testCsprojPath, "utf8");
  const patched = csprojWithProfilerRefs(csprojXml, PROFILER_ASSEMBLIES, `..\\${PROFILER_LIB_DIR}`);
  if (patched !== csprojXml) {
    await fs.promises.writeFile(testCsprojPath, patched);
    context.channel.appendLine(`[Profiler] Added replay assembly references to ${testProjectName}.csproj`);
  }

  const testFilePath = path.join(testProjectDir, `${className}.cs`);
  await fs.promises.writeFile(
    testFilePath,
    replayTestSource({
      framework,
      namespaceName: testProjectName.replace(/[^A-Za-z0-9_.]/g, "_"),
      className,
      pluginTypeName,
      pluginAssemblyFileName,
      profileFileName: picked,
    }),
  );
  context.channel.appendLine(`[Profiler] Generated ${testFilePath}`);

  const document = await vscode.workspace.openTextDocument(testFilePath);
  await vscode.window.showTextDocument(document);
  vscode.window.showInformationMessage(`Replay test ${className} generated — set breakpoints in ${pluginTypeName} and debug it from the Test Explorer.`);
}
