import * as vscode from "vscode";
import * as fs from "fs";
import * as path from "path";
import DataversePowerToolsContext from "../context";
import { parseConnectionString, normalizeOrganizationUrl } from "../general/connectionString";
import { filterRestoreNoise } from "../general/restoreDependencies";
import { activeComponentRoot } from "../components/componentDiscovery";

// Typings are generated by a bundled, cross-platform build of XrmDefinitelyTyped (net8, run via
// `dotnet`) that authenticates with the access token the extension already holds — so it works
// under BOTH service-principal and interactive (OAuth) connections, on Windows/macOS/Linux, with
// no Windows-only .exe and no client secret required for interactive users (#78, fixes #91).
// The tool reads the token from the DVPT_TOKEN environment variable and does no login of its own.

/** Path to the bundled net8 XrmDefinitelyTyped tool DLL inside the extension. */
export function bundledTypingsToolPath(context: DataversePowerToolsContext): string {
  return path.join(context.vscode.extensionPath, "tools", "xrmdefinitelytyped", "XrmDefinitelyTyped.dll");
}

/**
 * Build the argument list for the typings tool. Pure (no vscode/child_process) so it is
 * unit-testable and the flags are reviewable in one place. Paths use path.join so they are correct
 * off-Windows (the old code hard-coded `typings\XRM` / `webresources_src\lib`). Auth is supplied
 * out-of-band via DVPT_TOKEN, so no /method or client-secret flags are passed.
 */
export function buildTypingsArgs(params: { toolDll: string; orgUrl: string; solutionName: string; formIntersect?: { name: string; forms: { formId: string }[] }[] }): string[] {
  const solution = params.solutionName;
  const args = [
    params.toolDll,
    `/url:${params.orgUrl}`,
    `/out:${path.join("typings", "XRM")}`,
    `/ss:${solution}`,
    `/mfaReturnUrl:${params.orgUrl}`,
    `/jsLib:${path.join("webresources_src", "lib")}`,
    `/w:${solution}Web`,
    `/r:${solution}Rest`,
  ];
  if (params.formIntersect && params.formIntersect.length > 0) {
    args.push(`/fi:${params.formIntersect.map((intersect) => `${intersect.name}: ${intersect.forms.map((form) => form.formId).join(";")}`).join(" ")}`);
  }
  return args;
}

export async function generateTypings(context: DataversePowerToolsContext): Promise<void> {
  await vscode.window.withProgress(
    {
      location: vscode.ProgressLocation.Notification,
      title: "Generating Typings...",
    },
    async () => {
      await generateTypingsExecution(context);
    },
  );
}

export async function generateTypingsExecution(context: DataversePowerToolsContext): Promise<void> {
  const workspacePath = activeComponentRoot(context);
  if (!workspacePath) {
    return;
  }

  // Need a live connection to mint the token the tool authenticates with.
  if (!context.dataverse || !context.dataverse.isValid) {
    const initialised = context.dataverse ? await context.dataverse.initialize() : false;
    if (!initialised) {
      vscode.window.showErrorMessage("Connect to Dataverse before generating typings.");
      return;
    }
  }
  const orgUrl = normalizeOrganizationUrl(parseConnectionString(context.connectionString).url) || normalizeOrganizationUrl(context.dataverse.organizationUrl);
  if (!orgUrl) {
    vscode.window.showErrorMessage("No Dataverse organisation URL is available for typings generation.");
    return;
  }

  const toolDll = bundledTypingsToolPath(context);
  if (!fs.existsSync(toolDll)) {
    context.channel.appendLine(`The typings tool was not found at ${toolDll}. Reinstall the extension.`);
    context.channel.show();
    vscode.window.showErrorMessage("The bundled typings tool is missing. See the Dataverse PowerTools output for details.");
    return;
  }

  let token: string | undefined;
  try {
    token = await context.dataverse.getAuthorizationToken();
  } catch {
    token = undefined;
  }
  if (!token) {
    vscode.window.showErrorMessage("Could not obtain a Dataverse access token for typings generation.");
    return;
  }

  const args = buildTypingsArgs({ toolDll, orgUrl, solutionName: context.projectSettings.solutionName ?? "", formIntersect: context.projectSettings.formIntersect });

  const cp = require("child_process");
  // eslint-disable-next-line @typescript-eslint/naming-convention -- DVPT_TOKEN is an env var name.
  const childEnv = { ...process.env, DVPT_TOKEN: token };
  await new Promise<void>((resolve) => {
    // dotnet is a real executable (not a .cmd shim), so execFile spawns it directly. The token is
    // passed via the environment, never on the command line.
    const child = cp.execFile("dotnet", args, { cwd: workspacePath, env: childEnv, maxBuffer: 1024 * 1024 * 20 }, (error: unknown) => {
      if (error) {
        vscode.window.showInformationMessage("Error creating types, see output for details.");
        context.channel.show();
      } else {
        context.channel.appendLine("Typings have been generated.");
        vscode.window.showInformationMessage("Typings have been generated.");
      }
      resolve();
    });
    const emit = (d: unknown) => {
      const cleaned = filterRestoreNoise(String(d).trimEnd());
      if (cleaned) {
        context.channel.appendLine(cleaned);
      }
    };
    child.stdout?.on("data", emit);
    child.stderr?.on("data", emit);
  });
}
